GET http://localhost:8080/api/posts

###

GET http://localhost:8080/api/posts/1

###

POST  http://localhost:8080/api/posts
Content-Type: application/json

{
    "titulo": "Aprendendo Node.js",
    "texto": "Meu texto",
    "userId": 60
}

###
PUT http://localhost:8080/api/posts?id=1
Content-Type: application/json

{
    "titulo": "Desaprendendo PHP",
    "texto": "Meu novo texto"
}

###
DELETE http://localhost:8080/api/posts?id=1