GET http://localhost:8080/api/posts

###

GET http://localhost:8080/api/posts/1

###

POST  http://localhost:8080/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsImVtYWlsIjoiY2FpeGFwcmV0YUBnbWFpbC5jb20iLCJpYXQiOjE3MzE5NDgwMDEsImV4cCI6MTczMTk1MDQwMX0.zXCFvbBG7uLwfrynirOph7pJP2oJo5SUYWHhqxVyPOQ

{
    "titulo": "IHC 2.0",
    "texto": "Meu texto",
    "userId": 5
}

###
PUT http://localhost:8080/api/posts?id=1
Content-Type: application/json

{
    "titulo": "Desaprendendo PHP",
    "texto": "Meu novo texto"
}

###
DELETE http://localhost:8080/api/posts?id=1