
GET http://localhost:8080/api/usuarios

###

POST http://localhost:8080/api/usuarios
content-type: application/json

{
    
    "email": "agilebranco@gmail.com",
    "senha": "passounoteste"
}

###

PUT http://localhost:8080/api/usuarios/1
content-type: application/json

{
    "email": "Carlosdasilva@gmail.com",
    "senha": "Outrasenha"
}

###

DELETE http://localhost:8080/api/usuarios/1