
GET http://localhost:8080/api/usuarios

###

POST http://localhost:8080/api/usuarios
content-type: application/json

{
    
    "email": "jaycegod@gmail.com",
    "senha": "70denovo"
}

###

PUT http://localhost:8080/api/usuarios/1
content-type: application/json

{
    "email": "Carlosdasilva@gmail.com",
    "senha": "Outrasenha"
}

###

DELETE http://localhost:8080/api/usuarios/7

###

POST http://localhost:8080/api/usuarios/login
Content-Type: application/json

{
    "email": "caixapreta@gmail.com",
    "senha": "sextanoite"
}